### ISSUE TITLE
minus values seem to not work?

### ISSUE THREAD

**Issue by 0xsven** [zeusdeux/isInViewport#25] opened 2016-06-08 08:58 UTC
Hi I implemented isInViewport with the minus value. I am looping this for testing every 50ms:

`$('.anim:in-viewport(' -200 ')').addClass('active');`

My understanding is that on a viewport height of 1000px this would add the active class to all items within the first 800px? 

It seems to work fine if you scroll slowly. As soon as I scroll faster it doesn't add the class anymore. Can you help me resolve that issue?

**Comment by zeusdeux** [comment] 2016-06-29 23:13
Your understanding is correct and this should work as expected. Could you please provide a simple test that reproduces this issue for me to investigate further? Thanks.

**Comment by zeusdeux** [comment] 2016-10-14 19:55
Closing this since there hasn't been any activity here for a while. Feel free to reopen this if you feel the need to.

**Closed by zeusdeux** 2016-10-14 19:55 UTC
